# дз 7 часть 2 Корягина Алена

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg 

## 1

In [4]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

## 2

In [10]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [11, 4, -7]], float)
B = np.array([1, 7, 12, 15]) 
np.linalg.lstsq(A, B)

/tmp/ipykernel_52936/2275188674.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.19569081, -0.78588133, -0.72782264]),
 array([0.50512924]),
 3,
 array([14.79417262,  9.36986633,  1.82703628]))

## 3

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
print(np.linalg.det(A))
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

0.0
[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[0, 0, 0]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


(2, 2)

## 4

In [49]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(f'L = \n {L}')
print(f'U = \n {U}')
print(f'Check P * A = L * U: \n {np.dot(P.transpose(), A) - np.dot(L, U)}')

B = np.array([4, 3, 9])
np.linalg.solve(A, B)

L = 
 [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U = 
 [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
Check: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([ 4.81481481, -0.46296296,  0.03703704])